const $=s=>document.querySelector(s);const prompt=$('#prompt');let rows=[],serial=0;const example='这个卧室需要双人床、更多收纳，还想留一个小办公区，预算 18000 元，不要显得太挤';const groups=[['must','必须满足','设计要满足的需求'],['prefer','偏好','在可行的范围内优先考虑'],['lock','保持不变','不希望被调整的家具或空间条件']];
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',3500)}
$('#enter').onclick=()=>{$('#products').hidden=true;$('#agent').hidden=false;prompt.focus()};$('#back').onclick=()=>{$('#agent').hidden=true;$('#products').hidden=false};
function sync(){$('#send').disabled=!prompt.value.trim()}prompt.oninput=sync;$('#example').onclick=()=>{prompt.value=example;sync();prompt.focus()};document.querySelectorAll('[data-chip]').forEach(b=>b.onclick=()=>{const t=b.dataset.chip;if(!prompt.value.includes(t))prompt.value+=(prompt.value.trim()?'，':'')+t;sync();prompt.focus()});
function add(type,text){if(!rows.some(r=>r.text===text&&r.type===type))rows.push({id:++serial,type,text})}
function parse(text){let parts=text.split(/[，,。；;\n、]+/).map(s=>s.trim()).filter(Boolean);for(let p of parts){let type=/保留|保持|不动|不能移动|不要移动|不改变|不改动|固定/.test(p)?'lock':/希望|尽量|喜欢|风格|太挤|拥挤|通透|优先|偏好|简约|温馨/.test(p)?'prefer':'must';add(type,p)}}
function render(){const root=$('#constraints');root.replaceChildren();groups.forEach(([type,label,desc])=>{const box=document.createElement('section');box.className='group';const title=document.createElement('div');title.className='group-title';title.textContent=label;const n=document.createElement('small');n.textContent=rows.filter(r=>r.type===type).length+' 项';title.append(n);box.append(title);const d=document.createElement('div');d.className='group-desc';d.textContent=desc;box.append(d);const list=rows.filter(r=>r.type===type);if(!list.length){const e=document.createElement('div');e.className='empty';e.textContent=type==='lock'?'暂未指定，可按需添加':'暂无，可按需添加';box.append(e)}list.forEach(r=>{const line=document.createElement('div');line.className='constraint';const input=document.createElement('input');input.value=r.text;input.placeholder='输入一条约束';input.setAttribute('aria-label',label+'约束');input.oninput=()=>{r.text=input.value;invalidate()};const sel=document.createElement('select');sel.setAttribute('aria-label','更改约束分类');groups.forEach(([v,l])=>{const o=document.createElement('option');o.value=v;o.textContent=l;sel.append(o)});sel.value=r.type;sel.onchange=()=>{r.type=sel.value;invalidate();render()};const del=document.createElement('button');del.className='remove';del.textContent='×';del.setAttribute('aria-label','删除约束');del.onclick=()=>{rows=rows.filter(x=>x.id!==r.id);invalidate();render()};line.append(input,sel,del);box.append(line)});const a=document.createElement('button');a.className='add';a.textContent='＋ 添加一条';a.onclick=()=>{rows.push({id:++serial,type,text:''});invalidate();render();const inputs=$('#constraints').querySelectorAll('input');Array.from(inputs).find(i=>!i.value)?.focus()};box.append(a);root.append(box)});$('#count').textContent=rows.length+' 条约束'}
function invalidate(){$('#handoff').hidden=true;$('#start').hidden=false}$('#input-form').onsubmit=e=>{e.preventDefault();const text=prompt.value.trim();if(!text)return;parse(text);$('#user-message').textContent=text;$('#welcome').hidden=true;$('#brief').hidden=false;invalidate();render();prompt.value='';prompt.placeholder='还有想补充或调整的吗？';sync();$('#conversation').scrollTop=0};prompt.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('#input-form').requestSubmit()}};
$('#start').onclick=()=>{if(!rows.length||rows.some(r=>!r.text.trim())){toast('请填写空白约束，或删除不需要的条目');return}$('#handoff').hidden=false;$('#start').hidden=true;$('#handoff').scrollIntoView({behavior:'smooth',block:'nearest'})};$('#continue').onclick=invalidate;
$('#save').onclick=()=>{try{localStorage.setItem('kreativ-brief',JSON.stringify({rows,prompt:prompt.value,message:$('#user-message').textContent}));toast('需求草稿已保存到当前浏览器')}catch{toast('当前浏览器暂时无法保存草稿')}};try{const saved=JSON.parse(localStorage.getItem('kreativ-brief'));if(saved){rows=saved.rows||[];serial=Math.max(0,...rows.map(r=>r.id));prompt.value=saved.prompt||'';sync();if(rows.length){$('#welcome').hidden=true;$('#brief').hidden=false;$('#user-message').textContent=saved.message||'已恢复保存的需求';render()}}}catch{}$('#help').onclick=()=>toast('本原型验证需求输入与整理；房间为参考静态画布，尚未接入真实设计能力。');
const products=[['双人床','床架，带储物空间','¥ 1,999','床','0px -411px'],['三斗抽屉柜','白色，简洁收纳','¥ 599','收纳','-235px -170px'],['松木床头柜','松木，双抽屉','¥ 299','收纳','-120px -410px'],['八斗抽屉柜','白色，大容量收纳','¥ 1,299','收纳','-235px -413px']];function catalog(q=''){const root=$('#product-grid');root.replaceChildren();products.filter(p=>p.join('').includes(q)).forEach(p=>{const el=document.createElement('article');el.className='product';const photo=document.createElement('div');photo.className='product-photo';photo.style.backgroundPosition=p[4];const h=document.createElement('h4');h.textContent=p[0];const d=document.createElement('p');d.textContent=p[1];const price=document.createElement('strong');price.textContent=p[2];el.append(photo,h,d,price);root.append(el)});if(!root.children.length)root.textContent='暂无匹配的示例商品'}catalog();$('#search').oninput=e=>catalog(e.target.value);document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');catalog(b.dataset.filter)});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const active=b.dataset.tab==='添加';$('#catalog').hidden=!active;$('.search').hidden=!active;$('#tab-empty').hidden=active;$('#tab-empty').textContent=b.dataset.tab==='列表'?'房间中还没有添加家具。':'暂时没有收藏的商品。'});
