import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
export function createRoom(){
const host=document.querySelector('#viewport'), layer=document.querySelector('#annotations');
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(0xe9ebed,1);host.replaceChildren(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.1,100);camera.position.set(-7,6.7,8);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.7,0);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=6;controls.maxDistance=15;controls.maxPolarAngle=Math.PI/2.08;controls.minPolarAngle=.08;
scene.add(new THREE.HemisphereLight(0xffffff,0x9c8f7f,1.9));const sun=new THREE.DirectionalLight(0xfff7e8,2);sun.position.set(2,8,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-6,right:6,top:6,bottom:-6});sun.shadow.bias=-.001;scene.add(sun);
const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.85});const white=mat(0xf7f5f0),oak=mat(0xc6a581),wall=mat(0xf4f4f2),blue=mat(0x728b9c),dark=mat(0x58636b);
function box(g,w,h,d,x,y,z,m){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);return mesh}
const room=new THREE.Group();scene.add(room);box(room,4.98,.17,4.38,0,-.11,0,white);
for(let z=0;z<21;z++)for(let x=0;x<4;x++){let w=1.2;box(room,w-.014,.04,.194,-1.8+x*1.2,.0,-2+z*.2,mat(new THREE.Color().setHSL(.095,.25,.59+((x*13+z*7)%9)*.011)))}
const back=new THREE.Group(),right=new THREE.Group();room.add(back,right);
// Back wall with a doorway on the right.
box(back,3.25,2.65,.12,-.775,1.325,-2.16,wall);box(back,.35,2.65,.12,2.225,1.325,-2.16,wall);box(back,1.2,.45,.12,1.45,2.425,-2.16,wall);box(back,.87,2.15,.065,1.61,1.075,-2.12,white);box(back,.08,.045,.1,1.9,1.04,-2.04,dark);
// Window in the right wall, adjacent to the desk position.
box(right,.12,.92,4.2,2.46,.46,0,wall);box(right,.12,.58,4.2,2.46,2.36,0,wall);box(right,.12,1.15,1.35,2.46,1.495,-1.425,wall);box(right,.12,1.15,1.35,2.46,1.495,1.425,wall);
const glass=new THREE.MeshStandardMaterial({color:0xb8d7e2,transparent:true,opacity:.55,roughness:.2,side:THREE.DoubleSide});box(right,.025,1.1,1.5,2.455,1.495,0,glass);for(const z of [-.77,0,.77])box(right,.15,1.17,.035,2.44,1.495,z,white);box(right,.22,.06,1.66,2.39,.91,0,white);box(right,.14,.05,1.6,2.44,2.09,0,white);
// Low left wall keeps furniture visible in dollhouse view.
box(room,.12,.15,4.2,-2.46,.075,0,white);box(room,4.8,.1,.045,0,.07,-2.085,white);
const objects={};let cfg={},progress=0,active=null,showReasons=true;const animations=[];
function makeFurniture(key){const g=new THREE.Group();scene.add(g);objects[key]=g;return g}
const bed=makeFurniture('bed');box(bed,1.68,.28,2.12,0,.24,0,oak);box(bed,1.61,.23,2.03,0,.495,0,white);box(bed,1.65,.9,.09,0,.55,-1.05,oak);box(bed,1.62,.09,1.35,0,.65,.30,blue);for(const x of [-.4,.4])box(bed,.65,.13,.4,x,.665,-.69,white);
const storage=makeFurniture('storage');box(storage,1.65,1.85,.52,0,.945,0,oak);for(const x of [-.55,0,.55]){box(storage,.535,1.77,.035,x,.95,.28,white);box(storage,.022,.21,.04,x+.18,1.02,.315,dark)}
const desk=makeFurniture('desk');box(desk,.6,.075,1.2,0,.76,0,oak);for(const x of [-.25,.25])for(const z of [-.52,.52])box(desk,.055,.73,.055,x,.365,z,white);box(desk,.035,.38,.48,.17,1.0,0,dark);box(desk,.25,.018,.4,-.1,.808,0,white);box(desk,.45,.08,.45,-.65,.46,0,blue);box(desk,.07,.46,.45,-.86,.70,0,blue);for(const x of [-.8,-.49])for(const z of [-.15,.15])box(desk,.035,.42,.035,x,.21,z,dark);
const notes={bed:{title:'先把休息区安顿好',text:'床头靠墙，朝向房间的一侧留作上下床的通道。'},storage:{title:'收纳向上，少占地面',text:'沿墙集中收纳，把房间中部留给活动。'},desk:{title:'把自然光留给办公区',text:'书桌放在窗边，工作区与睡眠区分开。'}};
const pins={};Object.entries(objects).forEach(([key,g],i)=>{g.visible=false;const wrap=document.createElement('div');wrap.className='annotation';const pin=document.createElement('button');pin.className='pin';pin.textContent=i+1;pin.setAttribute('aria-label','查看'+({bed:'床',storage:'收纳柜',desk:'书桌'}[key])+'的设计原因');const bubble=document.createElement('div');bubble.className='reason-bubble';const top=document.createElement('div');top.className='reason-heading';const label=document.createElement('b');const close=document.createElement('button');close.textContent='×';close.setAttribute('aria-label','收起设计原因');const text=document.createElement('p');top.append(label,close);bubble.append(top,text);wrap.append(pin,bubble);layer.append(wrap);pin.onclick=()=>{active=active===key?null:key;updateNotes()};close.onclick=()=>{active=null;updateNotes()};pins[key]={wrap,pin,bubble,label,text};});
function updateNotes(){for(const [k,n] of Object.entries(pins)){n.label.textContent=notes[k].title;n.text.textContent=notes[k].text;n.bubble.hidden=active!==k;n.pin.classList.toggle('current',active===k);n.wrap.hidden=!objects[k].visible||!showReasons;}}
function configure(c){cfg=c;bed.scale.x=c.single?.64:1;bed.position.set(c.corner?-1.53:-1.28,0,-.96);storage.position.set(.45,0,-1.8);storage.scale.x=.85;storage.scale.y=c.moreStorage?1.15:1;desk.position.set(2.08,0,.15);notes.bed.text=c.corner?'床头和一侧临墙，释放房间中部空间；靠墙一侧上下床会不太方便。':'床头靠墙，朝向房间的一侧留作上下床的通道。';notes.storage.text=c.moreStorage?'用更高的柜体增加收纳，地面占用保持不变。':'沿墙集中收纳，把房间中部留给活动。';updateNotes();}
function stage(n){progress=n;let keys=['bed','storage','desk'];for(let i=0;i<keys.length;i++){const k=keys[i],g=objects[k],visible=n>=i+1&&cfg[k]!==false;if(visible&&!g.visible){g.position.y=.3;animations.push(g)}g.visible=visible;g.traverse(m=>{if(m.isMesh){if(!m.userData.original)m.userData.original=m.material; m.material=n<4?ghost:m.userData.original;}})}if(n>=1&&n<=3){active=cfg[keys[n-1]]===false?null:keys[n-1]}if(n===4)active=null;updateNotes();}
const ghost=new THREE.MeshStandardMaterial({color:0x89b7d2,transparent:true,opacity:.55,roughness:.8});
function fit(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(fit).observe(host);fit();
function frame(){requestAnimationFrame(frame);controls.update();for(let i=animations.length-1;i>=0;i--){const g=animations[i];g.position.y*=.85;if(g.position.y<.001){g.position.y=0;animations.splice(i,1)}}back.visible=camera.position.z>-2;right.visible=camera.position.x<2.5;renderer.render(scene,camera);for(const [key,n] of Object.entries(pins)){if(n.wrap.hidden)continue;const g=objects[key];const point=g.position.clone();point.y=key==='storage'?2.15:g.position.y+1.05;point.project(camera);const w=host.clientWidth,h=host.clientHeight;const x=(point.x*.5+.5)*w,y=(-point.y*.5+.5)*h;const px=Math.min(w-28,Math.max(28,x)),py=Math.min(h-70,Math.max(60,y)),bw=w<600?200:245;n.wrap.style.left=px+'px';n.wrap.style.top=py+'px';n.bubble.style.left=(Math.max(10,Math.min(w-bw-10,px-bw/2))-px)+'px';n.bubble.style.transform='none';n.bubble.style.bottom=py<180?'auto':'38px';n.bubble.style.top=py<180?'25px':'auto';n.wrap.style.visibility=point.z>1?'hidden':'visible';}}
updateNotes();frame();return {configure,stage,focus(k){active=k;updateNotes()},toggleReasons(v){showReasons=v;updateNotes()},reset(){camera.position.set(-7,6.7,8);controls.target.set(0,.7,0);controls.update()},top(){camera.position.set(0,10,.01);controls.target.set(0,0,0);controls.update()},zoom(v){camera.position.sub(controls.target).multiplyScalar(v).add(controls.target);controls.update()},snapshot(){return {stage:progress,visible:Object.keys(objects).filter(k=>objects[k].visible)}}};
}
