// State 2 uses a deterministic local scenario; progress follows actual scene updates.
let room3d=null,sceneModule=null,workActive=false,running=false,step=-1,timer=null,due=0,remaining=0,runConfig=null,steeringEvents=[],steeringSerial=0,designVersions=[],compareRooms=null,compareSyncing=false,activeVersion=1,feedbackSelection=null,localFeedbackTags=new Set(),lockedAreas=new Map(),dissatisfactionActive=false,briefEditSession=null,budgetConflictState='idle',serviceFailureState='idle',frozenProcess=false,currentChatTask=null,agentHeaderPending=false,errorPreviewSnapshot=null;
const simulateServiceFailure=new URLSearchParams(location.search).get('demo')==='service-error';
const stageNames=['安排空间','搭配家具','检查草案'];
const workActions=['正在安排休息、收纳与办公区域','正在安排收纳位置','正在安排窗边办公区','正在整理空间布局','正在补充家具细节','正在整理设计说明','正在整理草案与待核验事项'];
const phaseFor=s=>s<4?0:s<6?1:2;
const durations=[4500,6500,6500,6500,6500,7500,6000];
const spatialFeedbackToggle=document.createElement('button');spatialFeedbackToggle.id='spatial-feedback-toggle';spatialFeedbackToggle.disabled=true;spatialFeedbackToggle.setAttribute('aria-pressed','false');spatialFeedbackToggle.textContent='⌖ 在空间中指出';$('#reasons-toggle').before(spatialFeedbackToggle);
const lockFeedbackTag=document.createElement('button');lockFeedbackTag.type='button';lockFeedbackTag.dataset.localFeedback='锁定此区域';lockFeedbackTag.textContent='锁定此区域';$('#spatial-feedback-tags').append(lockFeedbackTag);
const sceneReady=import('./scene.js?v=17').then(m=>{sceneModule=m;room3d=m.createRoom();$('#scene-loading')?.remove();return room3d}).catch(err=>{$('#scene-error').hidden=false;$('#scene-loading')?.remove();$('#start').disabled=true;$('#start').textContent='三维场景不可用';console.error(err);return null});
function configFromBrief(){const text=rows.map(r=>r.text).join('，');const any=/床|收纳|柜|办公|书桌/.test(text);return {bed:!any||(/床/.test(text)&&!/不要.{0,3}床/.test(text)),storage:!any||(/收纳|柜/.test(text)&&!/不要.{0,3}(收纳|柜)/.test(text)),desk:!any||(/办公|书桌/.test(text)&&!/不要.{0,3}(办公|书桌)/.test(text)),single:/单人床/.test(text),corner:/两面靠墙|两侧靠墙|床.{0,4}靠角落|更多活动|太挤|拥挤/.test(text),moreStorage:/更多收纳|增加收纳|高柜/.test(text)}}
function summary(){const el=$('#brief-summary-list');el.replaceChildren();rows.forEach(r=>{const type=r.type==='lock'?'must':r.type;const p=document.createElement('p');p.textContent=(groups.find(g=>g[0]===type)||groups[0])[1]+' · '+r.text;el.append(p)})}
function compactRequirement(text){return text.replace(/^这个卧室需要/,'').replace(/^还想/,'').replace(/^需要/,'').trim()}
function carryConstraints(exclude=''){return rows.filter(r=>r.text.trim()&&r.text!==exclude).map(r=>compactRequirement(r.text)).slice(0,5)}
function appendUserChat(text){const root=$('#work-chat');if(root.lastElementChild?.classList.contains('chat-user')&&root.lastElementChild.textContent===text)return;root.hidden=false;const item=document.createElement('div');item.className='chat-user';item.textContent=text;root.append(item);agentHeaderPending=true;requestAnimationFrame(()=>item.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'}))}
function appendAgentChat(text){const root=$('#work-chat');root.hidden=false;const item=document.createElement('article');item.className='chat-agent';const showHeader=agentHeaderPending||!root.querySelector('.chat-agent');if(showHeader){const head=document.createElement('div');head.innerHTML='<span>✦</span><b>Agent</b>';item.append(head)}const p=document.createElement('p');p.textContent=text;item.append(p);agentHeaderPending=false;root.append(item);requestAnimationFrame(()=>item.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'}));return item}
function addReplyChoices(item,title,choices){const wrap=document.createElement('div');wrap.className='chat-choices';const label=document.createElement('b');label.textContent=title;const options=document.createElement('div');choices.forEach(({label,hint,onselect})=>{const button=document.createElement('button');button.type='button';button.innerHTML='<span></span><small></small>';button.querySelector('span').textContent=label;button.querySelector('small').textContent=hint||'';button.onclick=onselect;options.append(button)});wrap.append(label,options);item.append(wrap)}
function freezeForInstruction(){if(!frozenProcess){if(running)pause();frozenProcess=true;$('#process-status').textContent=step>=7?'已完成':'已暂停'}else if(currentChatTask?.dataset.state==='running'){setChatTask('paused','已暂停，等待新的调整方向');currentChatTask.open=false}clearTimeout(timer);running=false}
function startChatTask(text,details=[]){const root=$('#work-chat');const task=document.createElement('details');task.className='chat-task';task.dataset.state='running';task.open=true;task._resultDetails=details.filter(t=>!/保持不变|继续保留|未提及/.test(t));task.innerHTML='<summary><b>这一步的设计过程</b><span>进行中</span><i>⌄</i></summary><div class="chat-task-body"><span class="kreativ-builder" aria-hidden="true"><svg viewBox="0 0 32 32"><path class="builder-home" d="M4.5 13 16 4.5 27.5 13v14.5h-23V23"/><path class="builder-wall" d="M4.5 17v2.5M4.5 21.5V24"/><g class="builder-pencil"><path d="m9 22 2.2-5.2 9.7-7.2 3.2 4.3-9.7 7.2L9 22Z"/><path d="m20.9 9.6 3.2 4.3"/></g><rect class="builder-block" x="4.5" y="25" width="5" height="2.5" rx=".8"/></svg></span><p></p></div>';task.querySelector('p').textContent=text;root.append(task);currentChatTask=task;requestAnimationFrame(()=>task.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'}))}
function setChatTask(state,text){if(!currentChatTask)return;currentChatTask.dataset.state=state;currentChatTask.querySelector('summary span').textContent=state==='done'?'已完成':state==='decision'?'需要决定':state==='paused'?'已暂停':'进行中';currentChatTask.querySelector('.chat-task-body p').textContent=text}
function finishChatTask(){if(!currentChatTask)return;setChatTask('done','本次调整过程已完成');currentChatTask.open=false;const result=document.createElement('section');result.className='chat-result';const title=document.createElement('b');title.textContent='调整已完成';const list=document.createElement('ul');const details=currentChatTask._resultDetails?.length?currentChatTask._resultDetails:['已按本次指令更新空间方案'];details.forEach(t=>{const li=document.createElement('li');li.textContent=t;list.append(li)});const note=document.createElement('p');note.textContent='未修改的部分保持不变。展开上方“这一步的设计过程”可以回看执行过程。';result.append(title,list,note);$('#work-chat').append(result);requestAnimationFrame(()=>result.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'}))}
function budgetLimit(){const match=[...rows].reverse().map(r=>r.text.match(/预算[^0-9]*(\d+)/)).find(Boolean);return match?Number(match[1]):Infinity}
function shouldShowBudgetConflict(){return budgetConflictState==='idle'&&budgetLimit()<=5000&&runConfig?.bed&&runConfig?.storage&&runConfig?.desk}
function shouldShowServiceFailure(){return simulateServiceFailure&&serviceFailureState==='idle'&&step===5}
function syncWorkComposer(){const conflicted=budgetConflictState==='shown',serviceIssue=serviceFailureState==='shown'||serviceFailureState==='retrying',paused=workActive&&!running&&step<7&&!conflicted&&!serviceIssue;$('#pause-suggestions').hidden=!paused;prompt.placeholder=conflicted?'也可以直接说你更愿意调整哪一项…':serviceIssue?'当前草案已保留，也可以继续补充需求…':paused?'您暂停了当前方案，随时告诉我如何调整，直接说就好':'随时补充，例如：换成单人床…';$('.input-foot span').textContent=conflicted?'当前方案和已完成内容会保留':serviceIssue?'选择上方操作，或继续补充需求':paused?'可以修改建议后再发送':'也可以只说一句话'}
function showWork(){ $('#products').hidden=true;$('#agent').hidden=false;$('#conversation').hidden=true;$('#work-panel').hidden=false;$('#work-controls').hidden=false;$('#chips').hidden=true;$('.agent-top>span').textContent='规划与执行 · 02';$('.composer-note').textContent='三维布局演示 · 家具与尺寸为示例';syncWorkComposer();}
function startWork(initialPrompt=''){if(!rows.length||rows.some(r=>!r.text.trim())){toast('请填写或删除空白约束');return}if(!room3d){toast('三维房间正在准备，请稍后再试');return}briefEditSession=null;setBriefEditing(false);dissatisfactionActive=false;budgetConflictState='idle';serviceFailureState='idle';frozenProcess=false;currentChatTask=null;agentHeaderPending=false;setSpatialFeedbackMode(false);clearTimeout(timer);previousPhase=-1;steeringEvents=[];designVersions=[];activeVersion=1;$('#version-controls').hidden=true;$('#compare-layer').hidden=true;$('#plan').replaceChildren();$('#work-chat').replaceChildren();$('#work-chat').hidden=true;$('#process-group').open=true;$('#process-status').textContent='进行中';$('.brief-summary').open=false;$('#completion-note').textContent='商品价格、实际尺寸与开合条件仍需后续核验。';runConfig=configFromBrief();room3d.configure(runConfig);room3d.stage(0);step=0;running=true;workActive=true;remaining=0;$('#steering-message').hidden=true;summary();showWork();if(initialPrompt){appendUserChat(initialPrompt);appendAgentChat('好的，我会先安排空间、搭配家具，再检查预算与动线。设计过程中你可以随时暂停或补充想法。')}$('#work-panel').scrollTop=0;$('#scene-status').hidden=false;$('.header-actions>span').textContent='金额待核算';updateWork();schedule();}
let previousPhase=-1;
function updatePlan(){
 const done=step>=7,phase=done?3:phaseFor(step),changed=phase!==previousPhase;
 const past=[
 [step>=1?[runConfig.bed?'休息区位置已确定':'已跳过休息区',runConfig.bed?(runConfig.corner?'床头和一侧临墙，另一侧留作上下床通道。':'床头靠墙，面向房间留出通道。'):'本轮未要求放置床。']:null,step>=2?[runConfig.storage?'收纳位置已确定':'已跳过收纳区',runConfig.storage?'柜体沿墙集中布置。':'本轮未要求放置收纳柜。']:null,step>=3?[runConfig.desk?'办公区位置已确定':'已跳过办公区',runConfig.desk?'书桌放在窗边，与休息区分开。':'本轮未要求设置办公区。']:null],
 [step>=4?['已载入示例家具','占位已替换为床、柜体或桌椅的示例模型。']:null,serviceFailureState==='resolved'?['商品信息已恢复核验','价格与库存服务已经恢复，可以继续完成草案。']:serviceFailureState==='skipped'?['部分商品信息待核验','空间草案可正常查看，价格与库存稍后再核验。']:null,step>=6?['设计说明已整理','可点击画布中的圆点回看布局原因。']:null],
 [done?['示例草案已整理完成','房间布局与设计说明已展示。']:null,done?['保留待核验事项','商品价格、实际尺寸与开合条件尚未核验。']:null]
 ];
 if(!$('#plan').children.length)stageNames.forEach((name,i)=>{
 const d=document.createElement('details');d.className='task-node';const h=document.createElement('summary');h.innerHTML='<span class="node-icon"></span><b></b><span class="node-status"></span><span class="node-chevron">⌄</span>';h.querySelector('b').textContent=name;
 const body=document.createElement('div');body.className='node-body';const list=document.createElement('ol');list.className='node-log';const adjustments=document.createElement('div');adjustments.className='node-adjustments';const current=document.createElement('p');current.className='node-current';current.setAttribute('aria-live','polite');body.append(list,adjustments,current);d.append(h,body);$('#plan').append(d);
 });
 [...$('#plan').children].forEach((d,i)=>{
 const complete=i<phase,active=i===phase,adjusting=steeringEvents.some(e=>e.phase===i&&e.state==='active'),conflicted=i===1&&budgetConflictState==='shown',serviceIssue=i===1&&serviceFailureState==='shown',serviceRetrying=i===1&&serviceFailureState==='retrying';
 d.dataset.state=conflicted?'conflict':serviceIssue?'service-error':serviceRetrying?'current':complete?'done':active?'current':'pending';
 d.querySelector('.node-icon').textContent=conflicted||serviceIssue?'!':complete?'✓':i+1;
 d.querySelector('.node-status').textContent=conflicted?'需要决定':serviceIssue?'需要处理':serviceRetrying?'正在重新核验':complete?'已完成':active?(running?(adjusting?'正在调整':'进行中'):'已暂停'):'待开始';
 if(changed)d.open=active;
 const list=d.querySelector('.node-log');const entries=past[i].filter(Boolean);
 // Keep existing history nodes stable while users read them.
 if(list.children.length!==entries.length){list.replaceChildren();entries.forEach(([title,text])=>{const li=document.createElement('li');const b=document.createElement('b');b.textContent=title;const p=document.createElement('p');p.textContent=text;li.append(b,p);list.append(li)})}
 const adjustments=d.querySelector('.node-adjustments');adjustments.replaceChildren();const latestSteering=[...steeringEvents].reverse().find(e=>e.state!=='undone');steeringEvents.filter(e=>e.phase===i&&e.state!=='undone').forEach(e=>{
 const box=document.createElement('section');box.className='steer-event '+e.state;const head=document.createElement('div');head.className='steer-head';head.innerHTML='<span class="steer-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 7h5m4 0h7M9 4v6m6 4h5M4 14h7m4-3v6M4 20h11m4 0h1m-5-3v6"/></svg></span><b>方向调整</b><span></span>';head.lastElementChild.textContent=e.state==='active'?'已接收':'已更新';const quote=document.createElement('p');quote.className='steer-quote';quote.textContent='“'+e.text+'”';const intro=document.createElement('p');intro.className='steer-intro';intro.textContent='Agent 已更新本轮目标';const ul=document.createElement('ul');e.bullets.forEach(t=>{const li=document.createElement('li');li.textContent=t;ul.append(li)});box.append(head,quote,intro,ul);if(e.id===latestSteering?.id){const undo=document.createElement('button');undo.className='steer-undo';undo.textContent='撤销本次调整';undo.onclick=()=>undoSteering(e.id);box.append(undo)}adjustments.append(box)
 });
 if(conflicted){const card=document.createElement('section');card.className='budget-conflict';const flag=document.createElement('span');flag.textContent='预算与需求冲突';const title=document.createElement('b');title.textContent='5000 元内暂时找不到同时满足全部需求的组合';const copy=document.createElement('p');copy.textContent='空间布局已经保留。请选择这轮更希望优先满足什么。';const choices=document.createElement('div');[['raise','预算调至 6500 元','保留全部功能'],['core','优先床和收纳','暂缓办公区'],['flex','继续寻找其他组合','接受风格或容量变化']].forEach(([key,label,hint])=>{const button=document.createElement('button');button.innerHTML='<b></b><small></small>';button.querySelector('b').textContent=label;button.querySelector('small').textContent=hint;button.onclick=()=>resolveBudgetConflict(key);choices.append(button)});card.append(flag,title,copy,choices);adjustments.append(card)}
 if(serviceIssue){const card=document.createElement('section');card.className='budget-conflict service-failure';const flag=document.createElement('span');flag.textContent='部分商品信息暂未核验';const title=document.createElement('b');title.textContent='空间方案已经保留，不需要重新开始';const copy=document.createElement('p');copy.textContent='价格与库存服务暂时没有响应。你可以重新核验，或者先查看当前空间草案。';const reason=document.createElement('details');reason.innerHTML='<summary>查看原因</summary><p>商品价格与库存接口连接超时，空间布局与家具模型不受影响。</p>';const choices=document.createElement('div');[['retry','重新核验','推荐'],['draft','先看当前草案','稍后再核验']].forEach(([key,label,hint])=>{const button=document.createElement('button');button.innerHTML='<b></b><small></small>';button.querySelector('b').textContent=label;button.querySelector('small').textContent=hint;button.onclick=()=>key==='retry'?retryServiceFailure():continueWithDraft();choices.append(button)});card.append(flag,title,copy,reason,choices);adjustments.append(card)}
 if(serviceRetrying){const card=document.createElement('section');card.className='budget-conflict service-failure retrying';const flag=document.createElement('span');flag.textContent='正在重新核验';const title=document.createElement('b');title.textContent='正在重新连接商品服务…';const copy=document.createElement('p');copy.textContent='当前空间草案会继续保留。';card.append(flag,title,copy);adjustments.append(card)}
 const current=d.querySelector('.node-current');current.hidden=complete||conflicted||serviceIssue||serviceRetrying;current.classList.toggle('is-running',active&&running);
 current.replaceChildren();
 if(active&&running){
 const loader=document.createElement('span');loader.className='kreativ-builder';loader.setAttribute('aria-hidden','true');loader.innerHTML='<svg viewBox="0 0 32 32"><path class="builder-home" d="M4.5 13 16 4.5 27.5 13v14.5h-23V23"/><path class="builder-wall" d="M4.5 17v2.5M4.5 21.5V24"/><g class="builder-pencil"><path d="m9 22 2.2-5.2 9.7-7.2 3.2 4.3-9.7 7.2L9 22Z"/><path d="m20.9 9.6 3.2 4.3"/></g><rect class="builder-block" x="4.5" y="25" width="5" height="2.5" rx=".8"/></svg>';
 const label=document.createElement('span');const activeAdjustment=steeringEvents.find(e=>e.phase===i&&e.state==='active');label.textContent=activeAdjustment?.action||workActions[step];current.append(loader,label);
 }else current.textContent=active?'已暂停 · '+workActions[step].replace('正在','待继续'):'此阶段尚未开始。';
 });
 previousPhase=phase;
}
function updateWork(){
 const done=step>=7,phase=phaseFor(step),adjusting=steeringEvents.some(e=>e.phase===phase&&e.state==='active'),conflicted=budgetConflictState==='shown',serviceIssue=serviceFailureState==='shown'||serviceFailureState==='retrying';
 if(!frozenProcess){updatePlan();const process=$('#process-group');if(done){process.open=false;$('#process-status').textContent='已完成';[...$('#plan').children].forEach(node=>node.open=false)}else{process.open=true;$('#process-status').textContent=conflicted?'需要决定':serviceFailureState==='shown'?'需要处理':serviceFailureState==='retrying'?'正在恢复':running?'进行中':'已暂停'}$('#live-feedback').hidden=!done}
 $('#browse').hidden=!running||step<4||done;
 const canPoint=workActive&&step>=1&&Boolean(runConfig?.bed||runConfig?.storage||runConfig?.desk);spatialFeedbackToggle.disabled=!canPoint;if(!canPoint&&$('.canvas').classList.contains('feedback-active'))setSpatialFeedbackMode(false);
 $('#pause').textContent=running?'Ⅱ 暂停':'▶ 继续执行';$('#pause').hidden=done||conflicted||serviceIssue;
 $('#scene-status-text').textContent=done?'草案已就绪':conflicted?'预算与需求存在冲突':serviceFailureState==='shown'?'部分商品信息待处理':serviceFailureState==='retrying'?'正在重新核验商品信息':running?(adjusting?'正在按新方向调整':'正在'+stageNames[phase]):'已暂停 · 草案已保留';
 $('#scene-status').classList.toggle('paused',!running);$('.canvas-label>span').textContent=done?'空间草案':step<4?'布局草案':'家具草案';syncWorkComposer();
}
function schedule(){clearTimeout(timer);if(!running||step>=7)return;const conflict=step===4&&shouldShowBudgetConflict(),serviceIssue=shouldShowServiceFailure(),ms=remaining||(conflict||serviceIssue?2200:durations[step]);remaining=0;due=Date.now()+ms;timer=setTimeout(conflict?showBudgetConflict:serviceIssue?showServiceFailure:advance,ms)}
function showServiceFailure(){clearTimeout(timer);running=false;remaining=0;serviceFailureState='shown';previousPhase=-1;updateWork();toast('空间草案已保留，可以选择下一步')}
function retryServiceFailure(){if(serviceFailureState!=='shown')return;serviceFailureState='retrying';previousPhase=-1;updateWork();clearTimeout(timer);timer=setTimeout(()=>{serviceFailureState='resolved';running=true;remaining=0;$('#completion-note').textContent='商品价格与库存已完成核验；实际尺寸与开合条件仍需到店确认。';previousPhase=-1;updateWork();schedule();toast('商品服务已恢复，正在继续核验')},2400)}
function continueWithDraft(){if(serviceFailureState!=='shown')return;serviceFailureState='skipped';running=true;remaining=0;$('#completion-note').textContent='空间布局已经完成；部分商品价格与库存待稍后核验。';previousPhase=-1;updateWork();schedule();toast('已保留当前草案，稍后仍可继续核验')}
function enterErrorPreview(){
 if(!workActive){toast('请先开始设计，再从这里预览异常恢复');return}
 if(errorPreviewSnapshot)return;
 errorPreviewSnapshot={step,running,remaining:running?Math.max(100,due-Date.now()):remaining,budgetConflictState,serviceFailureState,frozenProcess,previousPhase,processOpen:$('#process-group').open,scrollTop:$('#work-panel').scrollTop,completionNote:$('#completion-note').textContent};
 clearTimeout(timer);budgetConflictState='resolved';serviceFailureState='shown';frozenProcess=false;running=false;remaining=0;step=5;room3d.stage(step);$('#demo-return').hidden=false;previousPhase=-1;updateWork();$('#process-group').open=true;requestAnimationFrame(()=>document.querySelector('.service-failure')?.scrollIntoView({behavior:'smooth',block:'center'}));
}
function exitErrorPreview(){
 if(!errorPreviewSnapshot)return;clearTimeout(timer);const saved=errorPreviewSnapshot;errorPreviewSnapshot=null;step=saved.step;running=saved.running;remaining=saved.remaining;budgetConflictState=saved.budgetConflictState;serviceFailureState=saved.serviceFailureState;frozenProcess=saved.frozenProcess;previousPhase=-1;$('#completion-note').textContent=saved.completionNote;$('#demo-return').hidden=true;room3d.stage(step);updateWork();$('#process-group').open=saved.processOpen;$('#work-panel').scrollTop=saved.scrollTop;previousPhase=saved.previousPhase;if(running)schedule();toast(running?'已返回，继续刚才的设计':'已返回刚才的任务状态')
}
function showBudgetConflict(){clearTimeout(timer);if(!shouldShowBudgetConflict())return schedule();running=false;remaining=0;budgetConflictState='shown';if(frozenProcess)setChatTask('decision','5000 元预算与全部功能需求存在冲突');const reply=appendAgentChat('我保留了已经完成的空间布局，但在 5000 元预算内，没有找到同时满足双人床、更多收纳和小办公区的商品组合。请先决定这轮更希望优先满足什么。');addReplyChoices(reply,'你更希望优先满足什么？',[{label:'预算调至 6500 元',hint:'保留全部功能',onselect:()=>resolveBudgetConflict('raise')},{label:'优先床和收纳',hint:'暂缓办公区',onselect:()=>resolveBudgetConflict('core')},{label:'继续寻找其他组合',hint:'接受风格或容量变化',onselect:()=>resolveBudgetConflict('flex')}]);previousPhase=-1;updateWork()}
function resolveBudgetConflict(key,alreadyShown=false){if(budgetConflictState!=='shown')return;const snapshot={rows:rows.map(r=>({...r})),config:{...runConfig},step,running:false};let label,reply,bullets;if(key==='raise'){label='预算调整至 6500 元';reply='我会把预算更新为 6500 元，保留全部功能需求，并继续匹配家具。';bullets=['预算更新至 6500 元','继续配置双人床、收纳和办公区'];rows=rows.map(r=>/预算/.test(r.text)?{...r,text:'预算 6500 元'}:r)}else if(key==='core'){label='优先床和收纳，办公区可以暂缓';reply='我会优先完成床和收纳，暂缓配置办公区，让核心需求先落地。';bullets=['优先满足双人床和更多收纳','本轮暂缓配置办公区'];rows=rows.filter(r=>!/办公|书桌/.test(r.text))}else{label='继续寻找其他组合，可以调整风格或收纳容量';reply='我会继续保留三个功能区，适当放宽家具风格和收纳容量，寻找更合适的组合。';bullets=['继续配置床、收纳和办公区','调整家具风格或收纳容量'];add('prefer','可调整家具风格或收纳容量')}if(!alreadyShown)appendUserChat(label);budgetConflictState='resolved';render();summary();runConfig=configFromBrief();room3d.configure(runConfig);room3d.stage(step);steeringEvents.forEach(e=>{if(e.state==='active')e.state='done'});steeringEvents.push({id:++steeringSerial,phase:1,text:label,action:'正在按新的优先级匹配家具',bullets,state:'active',snapshot});appendAgentChat(reply);if(frozenProcess)startChatTask('正在按新的优先级匹配家具',bullets);running=true;remaining=0;previousPhase=-1;updateWork();schedule();toast('已按你的选择继续搭配家具')}
function advance(){clearTimeout(timer);if(step>=7)return;step++;room3d.stage(step);remaining=0;const phase=step>=7?3:phaseFor(step);steeringEvents.forEach(e=>{if(e.state==='active'&&e.phase<phase)e.state='done'});if(frozenProcess&&step<7)setChatTask('running',workActions[step]);if(step>=7){running=false;saveCompletedVersion();if(frozenProcess)finishChatTask();toast('空间草案已就绪，可以查看了');}updateWork();schedule()}
function pause(){if(!running)return;remaining=Math.max(100,due-Date.now());clearTimeout(timer);running=false;updateWork()}
window.startKreativWork=initialPrompt=>{const request=initialPrompt||'';$('#example').disabled=true;sceneReady.then(room=>{$('#example').disabled=false;if(room)startWork(request)})};$('#start').onclick=()=>startWork();$('#pause').onclick=()=>{if(budgetConflictState==='shown')return;if(running){freezeForInstruction();appendUserChat('暂停当前方案');appendAgentChat('已暂停。当前草案、已经完成的内容和这些确认条件都已保留。');updateWork()}else{appendUserChat('继续执行');appendAgentChat('好的，我会从刚才暂停的位置继续。没有修改的条件保持不变。');if(frozenProcess)startChatTask(workActions[step]);running=true;updateWork();schedule()}};

function editBrief(){const wasRunning=running;if(wasRunning)pause();rows=rows.map(r=>r.type==='lock'?{...r,type:'must'}:r);briefEditSession={rows:rows.map(r=>({...r})),serial,wasRunning,remaining,step};dissatisfactionActive=false;setSpatialFeedbackMode(false);$('#scene-status').hidden=true;$('#work-panel').hidden=true;$('#work-controls').hidden=true;$('#conversation').hidden=false;$('#brief').hidden=false;$('#welcome').hidden=true;$('#chips').hidden=false;$('#pause-suggestions').hidden=true;$('.agent-top>span').textContent='重新梳理需求 · 01';$('#handoff').hidden=true;$('#start').hidden=false;$('#start').innerHTML='按新需求重新设计 <span>→</span>';prompt.placeholder='补充或修改你的需求…';workActive=false;setBriefEditing(true);render();invalidate();$('#conversation').scrollTop=0;}
function cancelBriefEdit(){if(!briefEditSession)return;rows=briefEditSession.rows.map(r=>({...r}));serial=briefEditSession.serial;remaining=briefEditSession.remaining;step=briefEditSession.step;const resume=briefEditSession.wasRunning&&step<7;briefEditSession=null;setBriefEditing(false);render();summary();workActive=true;$('#conversation').hidden=true;showWork();previousPhase=-1;running=resume;updateWork();$('#scene-status').hidden=false;if(running)schedule();$('#work-panel').scrollTop=0;}
$('#edit-brief').onclick=editBrief;$('#brief-cancel').onclick=cancelBriefEdit;
const originalEnter=$('#enter').onclick;$('#enter').onclick=()=>{if(workActive)showWork();else originalEnter()};let progressCueTimer=null,progressFocusTimer=null;
$('#return-work').onclick=()=>{
 if(!workActive){$('#enter').click();return}
 showWork();
 let target;
 if(step>=7){target=$('#live-feedback')}
 else{const node=$('#plan').children[phaseFor(step)];node.open=true;target=node.querySelector('.node-current')}
 clearTimeout(progressCueTimer);clearTimeout(progressFocusTimer);
 document.querySelectorAll('.progress-cue').forEach(el=>el.classList.remove('progress-cue'));
 const panel=$('#work-panel'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 requestAnimationFrame(()=>{
 const offset=target.getBoundingClientRect().top-panel.getBoundingClientRect().top+panel.scrollTop;
 panel.scrollTo({top:Math.max(0,offset-panel.clientHeight*.35),behavior:reduced?'instant':'smooth'});
 progressFocusTimer=setTimeout(()=>{
 if(!workActive||$('#agent').hidden)return;
 // Progress may advance during scrolling: cue the newest action, never an obsolete one.
 let latest=step>=7?$('#live-feedback'):$('#plan').children[phaseFor(step)].querySelector('.node-current');
 if(latest!==target){if(step<7)$('#plan').children[phaseFor(step)].open=true;const y=latest.getBoundingClientRect().top-panel.getBoundingClientRect().top+panel.scrollTop;panel.scrollTo({top:Math.max(0,y-panel.clientHeight*.35),behavior:'instant'})}
 latest.classList.remove('progress-cue');void latest.offsetWidth;latest.classList.add('progress-cue');
 progressCueTimer=setTimeout(()=>latest.classList.remove('progress-cue'),reduced?1250:3250);
 },reduced?0:350);
 });
};$('#browse').onclick=()=>{$('#agent').hidden=true;$('#products').hidden=false;toast('可以继续浏览，画布上会保留执行进度')};
document.querySelectorAll('[data-steer]').forEach(b=>b.onclick=()=>{const t=b.dataset.steer;if(!prompt.value.includes(t))prompt.value+=(prompt.value.trim()?'，':'')+t;sync();prompt.focus()});
function steeringPlan(text,currentPhase){
 if(/预算/.test(text))return {impact:1,action:currentPhase<1?'正在保留布局，并更新后续选品范围':'正在重新筛选预算范围内的家具',bullets:[text.match(/预算[^，。]*/)?.[0]||'更新家具预算','空间布局保持不变','重新筛选预算范围内的家具']};
 if(/单人床|双人床/.test(text))return {impact:0,action:'正在重新计算床与主要动线',bullets:[/单人床/.test(text)?'双人床改为单人床':'更新床的尺寸需求','收纳和办公区需求保持不变','重新计算床与主要动线']};
 if(/动线/.test(text))return {impact:0,action:'正在重新检查家具间距与通行空间',bullets:['主要动线不放置家具','现有功能区需求保持不变','重新检查家具间距与通行空间']};
 if(/办公|书桌/.test(text))return {impact:0,action:'正在重新安排办公区与周边空间',bullets:['更新办公区要求','床与收纳需求保持不变','重新检查窗边区域和通行空间']};
 return {impact:0,action:'正在按新方向更新空间布局',bullets:['已记录新的空间要求','未提及的需求保持不变','重新检查受影响的家具位置']};
}
function steeringReply(text){
 if(/预算/.test(text))return '我会按照“'+text+'”更新选品范围，当前空间草案会先保留，方便你随时回看。';
 if(/单人床/.test(text))return '我会把双人床换成单人床，并重新计算床与主要动线，当前草案会先保留。';
 if(/双人床/.test(text))return '我会按新的双人床需求重新计算休息区和主要动线，当前草案会先保留。';
 if(/动线/.test(text))return '我会按照“'+text+'”重新检查家具间距和通行空间，当前草案会先保留。';
 if(/办公|书桌/.test(text))return '我会按照“'+text+'”重新安排办公区与周边空间，当前草案会先保留。';
 return '我会按照“'+text+'”调整受影响的空间，当前草案会先保留，方便你随时回看。';
}
function lockedAreaForText(text){if(/整体|布局|空间|这里|区域/.test(text)&&lockedAreas.has('area'))return 'area';if(/床|休息/.test(text)&&lockedAreas.has('bed'))return 'bed';if(/收纳|柜/.test(text)&&lockedAreas.has('storage'))return 'storage';if(/办公|书桌/.test(text)&&lockedAreas.has('desk'))return 'desk';return null}
function removeAreaLock(key){const label=lockedAreas.get(key);lockedAreas.delete(key);rows=rows.filter(r=>r.text!==label+'保持不变');render();summary()}
function showLockedConflict(text,key){prompt.value='';sync();const label=lockedAreas.get(key),reply=appendAgentChat(label+'目前处于锁定状态。为了避免意外改动，我先停在这里。你可以保留锁定并继续原计划，或者解除锁定后执行这次调整。');addReplyChoices(reply,'这次希望怎么处理？',[{label:'保持锁定',hint:'不修改'+label,onselect:()=>{appendUserChat('保持'+label+'锁定');appendAgentChat('好的，'+label+'会继续保持不变，我将从刚才的位置继续。');frozenProcess=false;currentChatTask=null;running=step<7;previousPhase=-1;updateWork();if(running)schedule()}},{label:'解除锁定并调整',hint:'执行刚才的指令',onselect:()=>{appendUserChat('解除'+label+'锁定并继续调整');removeAreaLock(key);applySteering(text)}}])}
function applySteering(text){
 const snapshot={rows:rows.map(r=>({...r})),config:{...runConfig},step,running};const oldPhase=phaseFor(step),plan=steeringPlan(text,oldPhase);clearTimeout(timer);
 const lockedKey=lockedAreaForText(text);if(lockedKey){showLockedConflict(text,lockedKey);return}
 steeringEvents.forEach(e=>{if(e.state==='active')e.state='done'});
 if(/单人床|双人床/.test(text))rows=rows.filter(r=>!/床/.test(r.text));
 if(/预算/.test(text))rows=rows.filter(r=>!/预算/.test(r.text));
 if(/不要.{0,4}(办公区|书桌)/.test(text))rows=rows.filter(r=>!/办公|书桌/.test(r.text));
 parse(text);if(/预算/.test(text))budgetConflictState=/5000/.test(text)?'idle':'resolved';render();summary();runConfig=configFromBrief();room3d.configure(runConfig);
 if(plan.impact<oldPhase)step=plan.impact===0?3:4;
 room3d.stage(step);const event={id:++steeringSerial,phase:phaseFor(step),text,action:plan.action,bullets:plan.bullets,state:'active',snapshot};steeringEvents.push(event);appendAgentChat(steeringReply(text));if(frozenProcess)startChatTask(plan.action,plan.bullets);
 running=true;remaining=0;previousPhase=-1;activeVersion=1;if(designVersions.length)$('#version-controls').hidden=true;$('#compare-layer').hidden=true;$('#steering-message').hidden=true;prompt.value='';sync();updateWork();schedule();
 requestAnimationFrame(()=>{const box=document.querySelector('.steer-event.active');box?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'})});toast('已按新方向继续设计');
}
function undoSteering(id){
 const event=steeringEvents.find(e=>e.id===id);if(!event||event.state==='undone')return;clearTimeout(timer);rows=event.snapshot.rows.map(r=>({...r}));runConfig={...event.snapshot.config};step=event.snapshot.step;running=event.snapshot.running&&step<7;remaining=0;event.state='undone';room3d.configure(runConfig);room3d.stage(step);render();summary();previousPhase=-1;updateWork();if(running)schedule();toast('已撤销本次方向调整');
}
function completedVersionName(){const text=steeringEvents.map(e=>e.text).join('，');if(/单人床/.test(text)&&/预算/.test(text))return '单人床 · 低预算';if(/单人床/.test(text))return '单人床调整';if(/预算/.test(text))return '低预算调整';if(/动线/.test(text))return '动线优化';return '调整版'}
function saveCompletedVersion(){
 const version={config:{...runConfig},rows:rows.map(r=>({...r})),label:designVersions.length?'调整版':'初版'};if(!designVersions.length)designVersions=[version];else{version.label=completedVersionName();designVersions=[designVersions[0],version];activeVersion=1}
 const ready=designVersions.length===2;$('#version-controls').hidden=!ready;if(ready){$('#version-label').textContent='方案 2 / 2';$('#compare-version-name').textContent=designVersions[1].label}
}
function ensureCompareRooms(){
 if(compareRooms)return;const a=sceneModule.createRoom({host:$('#compare-view-a'),layer:$('#compare-notes-a'),notes:false,reasonsToggle:false}),b=sceneModule.createRoom({host:$('#compare-view-b'),layer:$('#compare-notes-b'),notes:false,reasonsToggle:false});compareRooms={a,b};a.onViewChange(v=>{if(compareSyncing)return;compareSyncing=true;b.setView(v);compareSyncing=false});b.onViewChange(v=>{if(compareSyncing)return;compareSyncing=true;a.setView(v);compareSyncing=false})
}
function openCompare(){if(designVersions.length<2)return;setSpatialFeedbackMode(false);$('#compare-layer').hidden=false;requestAnimationFrame(()=>{ensureCompareRooms();compareRooms.a.configure(designVersions[0].config);compareRooms.a.stage(7);compareRooms.b.configure(designVersions[1].config);compareRooms.b.stage(7);const view=room3d.getView();compareRooms.a.setView(view);compareRooms.b.setView(view);$('#compare-version-name').textContent=designVersions[1].label})}
function closeCompare(){if(compareRooms&&!$('#compare-layer').hidden)room3d.setView(compareRooms.b.getView());$('#compare-layer').hidden=true}
function useVersion(index){const v=designVersions[index];if(!v)return;rows=v.rows.map(r=>({...r}));runConfig={...v.config};step=7;running=false;activeVersion=index;room3d.configure(runConfig);room3d.stage(7);render();summary();previousPhase=-1;updateWork();$('.canvas-label>span').textContent='方案 '+(index+1)+' · 已选择';$('#version-label').textContent='方案 '+(index+1)+' / 2';closeCompare();toast('已选择方案 '+(index+1)+'，可继续提出调整')}
$('#compare-versions').onclick=openCompare;$('#close-compare').onclick=closeCompare;$('#use-version-one').onclick=()=>useVersion(0);$('#use-version-two').onclick=()=>useVersion(1);
function setSpatialFeedbackMode(on){const canvas=$('.canvas'),card=$('#spatial-feedback-card'),marker=$('#feedback-marker');canvas.classList.toggle('feedback-active',on);$('#viewport').classList.toggle('feedback-mode',on);spatialFeedbackToggle.setAttribute('aria-pressed',String(on));$('#spatial-feedback-prompt b').textContent='在空间里指出你想调整的位置';$('#spatial-feedback-prompt').hidden=!on;room3d?.setFeedbackMode(on,on?openSpatialFeedback:null);if(!on){card.hidden=true;marker.hidden=true;feedbackSelection=null;localFeedbackTags.clear()}}
function syncSpatialFeedbackInput(){const input=$('#spatial-feedback-text'),tokens=input.value.split(/[，,]/).map(t=>t.trim()).filter(Boolean);localFeedbackTags.clear();document.querySelectorAll('[data-local-feedback]').forEach(b=>{const selected=tokens.includes(b.dataset.localFeedback);b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));if(selected)localFeedbackTags.add(b.dataset.localFeedback)});$('#send-spatial-feedback').disabled=!input.value.trim()}
function openSpatialFeedback(selection){feedbackSelection=selection;localFeedbackTags.clear();document.querySelectorAll('[data-local-feedback]').forEach(b=>{b.classList.remove('selected');b.setAttribute('aria-pressed','false')});$('#spatial-feedback-text').value='';syncSpatialFeedbackInput();$('#feedback-location').textContent='已选择 · '+selection.label;const marker=$('#feedback-marker'),card=$('#spatial-feedback-card'),canvas=$('.canvas');marker.style.left=selection.x+'px';marker.style.top=selection.y+'px';marker.hidden=false;card.hidden=false;$('#spatial-feedback-prompt').hidden=true;requestAnimationFrame(()=>{const gap=18,cw=card.offsetWidth,ch=card.offsetHeight,w=canvas.clientWidth,h=canvas.clientHeight;const left=selection.x<w*.62?selection.x+gap:selection.x-cw-gap,top=selection.y<h*.56?selection.y+gap:selection.y-ch-gap;card.style.left=Math.max(12,Math.min(w-cw-12,left))+'px';card.style.top=Math.max(76,Math.min(h-ch-70,top))+'px';$('#spatial-feedback-text').focus()})}
function feedbackTarget(text){if(/床|休息/.test(text))return {key:'bed',label:'床和休息区'};if(/柜|收纳/.test(text))return {key:'storage',label:'收纳区域'};if(/书桌|办公/.test(text))return {key:'desk',label:'办公区域'};return {key:'area',label:'整体空间'}}
function spatialReply(selection,details){if(/太挤|拥挤/.test(details))return '我会重新检查家具间距和主要动线，让空间更松弛。';if(/位置不合理|布局不合适|摆放/.test(details))return '我会重新安排床、收纳和办公区的位置关系，先解决布局问题。';if(/家具不喜欢/.test(details))return '我会重新挑选家具款式，并检查它们与整体空间的搭配。';if(/整体方向需要调整|整体不对/.test(details))return '我会重新梳理空间布局和家具搭配方向，再生成一版。';if(/留空/.test(details))return '我会清理这个区域，并重新检查周围家具的位置。';return '我会根据“'+details+'”重点调整'+selection.label+'。'}
function lockSpatialArea(selection){lockedAreas.set(selection.key,selection.label);add('must',selection.label+'保持不变');render();summary();appendAgentChat('已锁定'+selection.label+'。后续调整会保留这里的位置和当前配置；如果新的指令涉及此区域，我会先请你确认是否解除锁定。');setSpatialFeedbackMode(false);toast(selection.label+'已锁定')}
function enterDissatisfaction(text){closeCompare();dissatisfactionActive=true;const note=$('#steering-message');note.className='';note.hidden=true;note.replaceChildren();const reply=appendAgentChat('听起来这一版还没对上你的期待。当前方案和已经确认的条件都已保留，我们先找出最需要调整的地方。');addReplyChoices(reply,'更接近哪一种情况？',[['空间太挤','太挤'],['布局不合适','位置不合理'],['家具不喜欢','家具不喜欢'],['整体不对','整体方向需要调整']].map(([label,detail])=>({label,hint:'',onselect:()=>{$('#spatial-feedback-text').value='';appendUserChat(label);applySpatialFeedback({key:'area',label:'整体空间'},detail)}})));const actions=document.createElement('div');actions.className='chat-reply-actions';const locate=document.createElement('button');locate.textContent='在空间中指出 →';locate.onclick=()=>{setSpatialFeedbackMode(true);$('#spatial-feedback-prompt').hidden=false;toast('点击右侧家具或区域即可添加反馈')};const restart=document.createElement('button');restart.textContent='重新梳理需求';restart.onclick=()=>{dissatisfactionActive=false;setSpatialFeedbackMode(false);editBrief()};actions.append(locate,restart);reply.append(actions);setSpatialFeedbackMode(true);$('#pause').hidden=true;$('#scene-status').hidden=false;$('#scene-status-text').textContent='等待你指出需要调整的位置';$('#scene-status').classList.add('paused');prompt.value='';prompt.placeholder='也可以直接说：床的位置不对…';sync()}
function applySpatialFeedback(selection,details){const snapshot={rows:rows.map(r=>({...r})),config:{...runConfig},step,running};clearTimeout(timer);steeringEvents.forEach(e=>{if(e.state==='active')e.state='done'});const locking=/锁定此区域/.test(details),adjustmentDetails=details.split(/[，,]/).map(t=>t.trim()).filter(t=>t&&t!=='锁定此区域').join('，'),leave=/这里应该留空/.test(adjustmentDetails),crowded=/太挤/.test(adjustmentDetails);if(locking){lockedAreas.set(selection.key,selection.label);add('must',selection.label+'保持不变')}if(leave){const remove={bed:'不要床',storage:'不要收纳柜',desk:'不要办公区'}[selection.key];if(remove)parse(remove);else add('must','此处空间保持留空')}if(crowded)add('prefer',selection.label+'周围需要更宽松');if(adjustmentDetails)add('prefer',selection.label+'：'+adjustmentDetails);render();summary();runConfig=configFromBrief();room3d.configure(runConfig);step=3;room3d.stage(step);const event={id:++steeringSerial,phase:0,text:selection.label+'：'+details,action:'正在重新安排'+selection.label+'，并保护其他区域',bullets:['重点优化'+selection.label,adjustmentDetails,locking?'调整完成后锁定此区域':'','其他家具与已确认需求保持不变'].filter(Boolean),state:'active',snapshot};steeringEvents.push(event);appendAgentChat(spatialReply(selection,adjustmentDetails)+(locking?' 调整完成后，我会锁定这个区域，后续不会直接改动。':''));if(frozenProcess)startChatTask('正在重新安排'+selection.label+'，并保护其他区域',['重点优化'+selection.label,adjustmentDetails,locking?'锁定'+selection.label:''].filter(Boolean));running=true;remaining=0;previousPhase=-1;activeVersion=1;dissatisfactionActive=false;$('#version-controls').hidden=true;$('#compare-layer').hidden=true;setSpatialFeedbackMode(false);const note=$('#steering-message');note.className='';note.hidden=true;prompt.value='';prompt.placeholder='随时补充，例如：换成单人床…';sync();updateWork();schedule();toast('正在按你的反馈调整')}
spatialFeedbackToggle.onclick=()=>{if(spatialFeedbackToggle.disabled)return;const on=!$('.canvas').classList.contains('feedback-active');setSpatialFeedbackMode(on);if(on)toast('点击家具或区域，指出你想调整的位置')};
document.querySelectorAll('[data-local-feedback]').forEach(b=>{b.setAttribute('aria-pressed','false');b.onclick=()=>{const input=$('#spatial-feedback-text'),tag=b.dataset.localFeedback,tokens=input.value.split(/[，,]/).map(t=>t.trim()).filter(Boolean),index=tokens.indexOf(tag);if(index>=0)tokens.splice(index,1);else tokens.push(tag);input.value=tokens.join('，');syncSpatialFeedbackInput();input.focus()}});$('#spatial-feedback-text').addEventListener('input',syncSpatialFeedbackInput);$('#close-spatial-feedback').onclick=()=>{$('#spatial-feedback-card').hidden=true;$('#feedback-marker').hidden=true;feedbackSelection=null;$('#spatial-feedback-prompt').hidden=false};$('#spatial-feedback-form').onsubmit=e=>{e.preventDefault();if(!feedbackSelection)return;const details=$('#spatial-feedback-text').value.trim();if(!details){toast('选择一个原因，或写下你的想法');return}appendUserChat(feedbackSelection.label+'：'+details);if(details==='锁定此区域'){lockSpatialArea(feedbackSelection);return}if(lockedAreas.has(feedbackSelection.key)&&!details.includes('解除锁定')){appendAgentChat(feedbackSelection.label+'已经锁定。请先解除锁定，再调整这个区域。');setSpatialFeedbackMode(false);return}freezeForInstruction();applySpatialFeedback(feedbackSelection,details)};
// First detect the user's attitude, then let `concrete` decide whether the
// message contains an actionable object or direction. Conversational fillers
// such as “呢 / 吧 / 感觉” must not turn vague dissatisfaction into a task.
const negativeFeedback=/不(?:太|怎么|是很|是特别)?(?:满意|好|行|对|合适|合理)|不符合(?:预期|想法|期待)|没(?:有)?达到(?:预期|期待)|不是我想要|不喜欢(?:这个|这版|目前|现在)?(?:方案|结果|布局)?|(?:感觉|看着|整体)?(?:一般|不太好|不怎么样)|差点意思|说不上来|很失望/;
const originalSubmit=$('#input-form').onsubmit;$('#input-form').onsubmit=e=>{if(!workActive)return originalSubmit(e);e.preventDefault();const text=prompt.value.trim();if(!text)return;freezeForInstruction();appendUserChat(text);const supported=/单人床|双人床|更多收纳|增加收纳|高柜|书桌|办公区|两面靠墙|两侧靠墙|预算|动线.{0,6}(不要|不放).{0,4}家具/.test(text),negative=negativeFeedback.test(text),concrete=/太挤|拥挤|位置|摆放|留空|不要|太大|太小|挡住|不方便|风格|颜色|色调|材质|预算|动线|收纳不足|光线|氛围|温馨|简约|家具.{0,4}不喜欢|不喜欢.{0,4}家具/.test(text);const note=$('#steering-message');if(budgetConflictState==='shown'){const key=/6500|提高|增加预算/.test(text)?'raise':/优先.{0,4}(床|收纳)|暂缓.{0,4}(办公|书桌)|不要.{0,4}(办公|书桌)/.test(text)?'core':'flex';prompt.value='';sync();resolveBudgetConflict(key,true)}else if(/暂停|停一下/.test(text)){note.hidden=true;appendAgentChat('已暂停。当前草案、已经完成的内容和这些确认条件都已保留。');prompt.value='';sync();updateWork()}else if(negative&&!concrete||dissatisfactionActive&&!concrete)enterDissatisfaction(text);else if(dissatisfactionActive||negative&&concrete){$('#spatial-feedback-text').value='';applySpatialFeedback(feedbackTarget(text),text)}else if(supported){dissatisfactionActive=false;setSpatialFeedbackMode(false);applySteering(text)}else{dissatisfactionActive=false;setSpatialFeedbackMode(false);applySteering(text)}};
$('#zoom-in').onclick=()=>room3d?.zoom(.9);$('#zoom-out').onclick=()=>room3d?.zoom(1.1);$('#reset-view').onclick=()=>{$('#view-3d').click()};$('#view-3d').onclick=()=>{room3d?.reset();$('#view-3d').classList.add('selected');$('#view-top').classList.remove('selected')};$('#view-top').onclick=()=>{room3d?.top();$('#view-top').classList.add('selected');$('#view-3d').classList.remove('selected')};$('#reasons-toggle').onclick=()=>{const v=$('#reasons-toggle').getAttribute('aria-pressed')!=='true';$('#reasons-toggle').setAttribute('aria-pressed',String(v));room3d?.toggleReasons(v)};
$('#help').onclick=enterErrorPreview;
$('#exit-error-preview').onclick=exitErrorPreview;
